# Generated by Django 4.2.1 on 2023-07-29 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cart_cartitem_cart_products_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='username',
        ),
    ]
